pkg/artifact/artifactfakes/fake_credentials_controller.go, pkg/error.go, pkg/http/core/applications.go, pkg/http/core/artifacts.go, pkg/http/core/core_test.go, pkg/http/core/credentials.go, pkg/http/core/manifest.go, pkg/http/core/ops.go, pkg/http/core/search.go, pkg/http/core/task.go, pkg/middleware/auth.go
- changes the func name from `WriteError` to `Error` since we aren't really writing anything, but instead attaching an error to the gin context
=> change func name to attach error to gin context

pkg/arcade/arcadefakes/fake_client.go, pkg/artifact/artifactfakes/fake_credentials_controller.go, pkg/fiat/fiatfakes/fake_client.go, pkg/helm/helmfakes/fake_client.go, pkg/http/core/core_test.go, pkg/http/core/credentials.go, pkg/http/core/credentials_test.go, pkg/http/core/payload_test.go, pkg/kubernetes/cached/disk/diskfakes/fake_cache_round_tripper.go, pkg/kubernetes/client.go, pkg/kubernetes/kubernetesfakes/fake_client.go, pkg/kubernetes/kubernetesfakes/fake_controller.go, pkg/sql/sqlfakes/fake_client.go
Listing namespaces was not timing out at 5 seconds like we were specifying in the `ListOptions`, so we now pass in a context with a timeout to our `ListbyGVR` func.
=> fix timeout when listing resources

pkg/error.go, pkg/http/core/applications.go, pkg/http/core/applications_test.go, pkg/http/core/artifacts_test.go, pkg/http/core/core_test.go, pkg/http/core/credentials.go, pkg/http/core/credentials_test.go, pkg/http/core/manifest_test.go, pkg/http/core/ops_test.go, pkg/http/core/search_test.go, pkg/http/core/task_test.go, pkg/logger.go, pkg/middleware/error.go, pkg/middleware/log.go
- Appends a unique GUID to all server side API errors which are returned to the UI
- Logs this error along with the GUID
- Logs the file, function, and line number that threw the error
This will be useful for when users complain about receiving an error that doesn't say much. We can now grep the logs for the error ID to show exactly where an error occurred in clouddriver and what that error is.
Clouddriver error logs look like this:
=> add clouddriver logger

pkg/http/core/kubernetes/ops.go, pkg/http/core/kubernetes/rollback.go, pkg/http/core/kubernetes/rollback_test.go
Adds support for "static" mode Undo Rollout Manifest which is triggered when the *Undo Rollout Manifest* stage is run. Additionally, it makes listing Replica Sets for a Deployment to rollback more efficient by specifying the namespace to filter on.
=> Rollback stage

pkg/http/v1/payload_test.go, pkg/http/v1/provider.go, pkg/http/v1/provider_test.go
- adds validation for base64 encoded CA data when onboarding a kubernetes provider. If invalid base64 CA data is passed return a descriptive error with a Bad Request.
NOTE: this is a patch to `v0.9.x`.
=> add base64 validation when onboarding kubernetes providers

pkg/http/core/kubernetes/deploy.go, pkg/http/core/kubernetes/deploy_test.go, pkg/http/core/kubernetes/kubernetes_test.go, pkg/kubernetes/controller.go, pkg/kubernetes/kubernetesfakes/fake_controller.go, pkg/kubernetes/sort.go, pkg/kubernetes/sort_test.go
- we now sort a list of manifests by their kind's priority before applying.
This is important when applying multiple different types of manifests. For example, kind `Namespace` has the lowest number priority and is therefore deployed first. This makes sense as other manifests may be deployed to this namespace. Failing to sort the manifests properly would result in a short-circuit failure where the deployment could not succeed (as the manifest would rely on the namespace existing).
The sort priority is taken from the source code [here](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesHandler.java#L128).
NOTE: this is a patch on release 0.9.x.
=> add logic to sort manifests by priority

pkg/helm/client.go, pkg/helm/client_test.go
- This makes our helm client loop through a resources defined URLs to get the resource, instead of assuming the resource is available at `https://example-helm-repo.com/chart_name-chart_version.tgz`
NOTE: this is a patch for release 0.9.x.
=> use a resources defined URLs when fetching a chart

Makefile, api/swagger.yaml, pkg/arcade/arcadefakes/fake_client.go, pkg/arcade/client.go, pkg/arcade/client_test.go, pkg/http/core/applications.go, pkg/http/core/credentials.go, pkg/http/core/kubernetes/cleanup.go, pkg/http/core/kubernetes/delete.go, pkg/http/core/kubernetes/deploy.go, pkg/http/core/kubernetes/patch.go, pkg/http/core/kubernetes/restart.go, pkg/http/core/kubernetes/rollback.go, pkg/http/core/kubernetes/runjob.go, pkg/http/core/kubernetes/scale.go, pkg/http/core/manifest.go, pkg/http/core/task.go, pkg/kubernetes/provider.go, pkg/kubernetes/version_test.go, pkg/middleware/error.go, pkg/sql/sql.go, pkg/sql/sql_test.go
For kubernetes accounts, add support for additional provider for retrieving auth tokens.  Kubernetes credentials are retrieved from [arcade](https://github.com/homedepot/arcade), which added support for `rancher` as a token provider in addition to `google`, the default provider.
The token provider is added to the `kubernetes_providers` table as a non-nullable column with a default value of `google`, which means that existing accounts will be assigned `google` when the table is altered to include the new column
```sql
TABLE `kubernetes_providers` (
`name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
`host` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
`ca_data` varchar(8192) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
`bearer_token` varchar(2048) COLLATE utf8mb4_unicode_ci …
```
=> Token provider

go.sum, pkg/artifact/artifactfakes/fake_credentials_controller.go, pkg/fiat/fiatfakes/fake_client.go, pkg/helm/helmfakes/fake_client.go, pkg/http/core/kubernetes/deploy.go, pkg/http/core/kubernetes/kubernetes_test.go, pkg/http/core/kubernetes/ops.go, pkg/kubernetes/cached/disk/diskfakes/fake_cache_round_tripper.go, pkg/kubernetes/controller.go, pkg/kubernetes/kubernetesfakes/fake_client.go, pkg/kubernetes/kubernetesfakes/fake_controller.go, pkg/kubernetes/kubernetesfakes/fake_manifest_filter.go, pkg/kubernetes/version.go, pkg/kubernetes/version_test.go, pkg/sql/sqlfakes/fake_client.go
**Fix versioning volumes bug**: the previous version of the code would only bind artifacts that are present in the list of the required artifacts for the stage and was breaking when we use one Deploy manifest stage for defining the artifact and the deployment that is binding that artifact. There was also another issue fixed with the volume name and the artifact name which the previous version of the code expected them to match.
=> Add map to save artifacts names and refrences

pkg/http/core/core_test.go, pkg/http/core/kubernetes/deploy.go, pkg/http/core/ops.go, pkg/http/core/ops_test.go, pkg/kubernetes/version.go
Go Clouddriver was occasionally returning an empty HTTP 200 response on the `/kubernetes/ops` endpoint calls. This was throwing an error [here](https://github.com/spinnaker/orca/blob/master/orca-clouddriver/src/main/java/com/netflix/spinnaker/orca/clouddriver/tasks/artifacts/CleanupArtifactsTask.java#L64) in orca: `null value in entry: kato.last.task.id=null`. The problem seemed intermittent but mostly seemed to happen in stages where a concurrently running stage failed and the pipeline was canceled.
=> fix cause of kato.last.task.id=null error

pkg/http/core/kubernetes/cleanup.go, pkg/http/core/kubernetes/cleanup_test.go, pkg/http/core/kubernetes/delete.go, pkg/http/core/kubernetes/delete_test.go, pkg/http/core/task.go, pkg/http/core/task_test.go, pkg/task.go
When a resource is deleted in Go Clouddriver it creates a task, which is then checked by Orca. Sometimes the resource is deleted before orca can grab the status of this task which is throwing an error 
```
<kind> "<name>" not found
```
Declare these tasks as kind `delete` and ignore these errors.
=> Fix delete race condition

pkg/http/core/applications.go, pkg/http/core/applications_test.go
A versioned resource contains its sequence in the `moniker.spinnaker.io/sequence` annotation. A resource which is owned by some deployment defines its sequence in the `deployment.kubernetes.io/revision` annotation.
This PR just gathers the sequence for resources from the `moniker.spinnaker.io/sequence`, otherwise it returns the sequence stored in the `deployment.kubernetes.io/revision` annotation.
=> fix sequence for versioned resources

pkg/http/core/applications.go, pkg/http/core/applications_test.go, pkg/http/core/payload_test.go
This PR fixes a few bugs where resources were not being associated with their correct Server Group Manager. We were originally relying on annotations provided by previous Spinnaker deployments. This changes that logic by relying solely on a resources `.metadata.ownerReference.UID` field in Kubernetes. Not only is this more efficient and reliable, it is far more accurate and ovoids the error of having resources associated with other resources of the same name in different namespaces.
Additionally I have added comments to this file to hopefully make it a bit easier to understand what's going on.
- add comments for the `/applications/*` endpoints in correct Go patterns
- associate pods with their owner by using owner UID
- associate replica sets with their deployment by using deployment UID …
=> associate server groups and managers using UID

api/swagger.yaml
Defines remaining CRUD paths for Kubernetes Providers
- `GET /v1/kubernetes/providers/{name}` to retrieve an existing kubernetes provider
- `PUT /v1/kubernetes/providers` to create, or replace if existing, a kubernetes provider
=> Add GET/PUT kubernetes providers paths

pkg/http/core/applications.go, pkg/http/core/applications_test.go, pkg/http/core/payload_test.go
I've noticed some pretty wonky things happening in the clusters page in Spinnaker. It isn't "breaking" but it is rather annoying. Sometimes on auto-refresh (not page refresh), UI elements will move around in a different order, and occasionally this causes the UI to look a bit "broken". 
I'm pretty sure this is an issue with us not sorting the server groups and server groups managers before returning the list. Before, we were sorting by name only, but this PR sorts all of these elements by account name (cluster), namespace, kind, and name, giving us a more ordered list of clusters in the UI.
Most of this PR is just extensive tests that return unsorted resources. For a source on the logic behind sorting by multiple elements, see [this stackoverflow …
=> sort resources by account, namespace, kind, and name

api/swagger.yaml, pkg/http/router.go, pkg/http/v1/provider.go, pkg/http/v1/provider_test.go, pkg/sql/sql.go, pkg/sql/sql_test.go, pkg/sql/sqlfakes/fake_client.go
This implements two new paths for kubernetes providers
- `GET /v1/kubernetes/providers/:name` which returns the kubernetes provider, with read/write permissions
- `PUT /vi/kubernetes/providers` which
- creates the provider and permissions when the provider does not already exist
- replaces the provider and permissions when the provider already exists
This also refactors the create read/write permissions functions, moving them out of `providers.go` and encapsulating them inside the create kubernetes provider function in `sql.go`, which follows the pattern done with delete permissions.
=> Adds GET/PUT operations for kubernetes providers

pkg/http/core/kubernetes/delete.go, pkg/http/core/kubernetes/delete_test.go, pkg/http/core/kubernetes/kubernetes_test.go, pkg/http/core/kubernetes/ops.go
There are two options that will set the deletion to cascade. Originally this was set when `options.cascading = true`, however in later APIs they have this set in `options.orphanDependants = false`. This PR fixes this problem by providing an `options.orphanDependants` pointer. It must be a pointer for backwards compatibility, so that older APIs which do not send this option are always set to cascade delete. For newer APIs which send this option, we check the option is `false` before setting the delete propagation.
=> fix delete cascade

pkg/http/core/applications.go, pkg/http/core/applications_test.go, pkg/kubernetes/client.go, pkg/kubernetes/controller.go, pkg/kubernetes/kubernetesfakes/fake_client.go
Listing resources concurrently was not working for clusters that were not available. We would get a timeout after 30 seconds (instead of the specified 10 in the request context) for *each* resource requested.
This was because for each resource requested in parallel we have to perform API discovery on the kubernetes dynamic client. This did not take into account the context timeout of 10 seconds and would therefore timeout after 30 seconds. Additionally, hidden in the client discovery code is a mutex lock around this discovery operation (see https://github.com/kubernetes/client-go/blob/f6ce18ae578c8cca64d14ab9687824d9e1305a67/restmapper/discovery.go#L194). So, concurrently requesting four resources would fail on the API discovery four times in a row, resulting in a 2 minute request!
This …
=> add discover ability for kube client

pkg/http/core/applications.go, pkg/http/core/applications_test.go, pkg/http/core/payload_test.go, pkg/kubernetes/service.go, pkg/kubernetes/service_test.go, pkg/kubernetes/statefulset.go, pkg/kubernetes/statefulset_test.go
Since this is a larger PR (most of it is just payload differences), I would recommend reviewing the `applications.go` file, in particular the functions `makeLoadBalancerServerGroupsMap` and `makeServerGroupLoadBalancersMap`. It should be noted that the `/applications/*/serverGroups` endpoint is now retrieving Kubernetes kind Services in addition to its other four resources. The `/applications/*/loadBalancers` endpoint is now retrieving 5 Kinds: Pods, ReplicaSets, StatefulSets, Services,		and Ingresses. Retrieval of pods seems necessary to build the expected response for the pages.
In summary, this PR:
- Fixes load balancers not being able to be deleted (API change was not setting namespace field correctly)
- Adds service info for ReplicaSets and StatefulSets that are fronted by a service …
=> add support for service info

pkg/http/core/applications.go
- Load balancers should only be associated with server groups if they are in the same cluster.
=> fix lb to server group association

cmd/clouddriver/clouddriver.go, pkg/artifact/controller.go, pkg/artifact/controller_test.go, pkg/artifact/test/helm-chart-basic-auth.json, pkg/helm/client.go, pkg/helm/client_test.go, pkg/helm/helmfakes/fake_client.go
This PR adds support for
1. Basic auth (username/password) to Helm artifact credentials
2. Defining a custom directory for the artifact credentials configuration files, rather than using the default `/opt/spinnaker/artifacts/confg`.  
- In our `go-clouddriver` deployment we maintain the credentials config in a Kubernetes ConfigMap which is mounted as a volume to the default directory location.  However, we want to store the credentials config in vault and use the [vault agent injector](https://www.vaultproject.io/docs/platform/k8s/injector) to make them available to `go-clouddriver`.  The vault agent injector writes to the `/vault` directory, so need the ability to use a directory different than the default.
=> Helm repository basic auth

pkg/http/core/kubernetes/restart.go, pkg/http/core/kubernetes/restart_test.go, pkg/http/core/kubernetes/rollback.go, pkg/http/core/kubernetes/rollback_test.go, pkg/http/core/kubernetes/scale.go, pkg/http/core/kubernetes/scale_test.go, pkg/http/core/task.go, pkg/http/core/task_test.go
Returns a `404 Not Found` for a `GET /task/:id` request when no kubernetes resources exist for the task ID.
Currently, when a task is not found, it returns a `200 OK` with a default response payload, which was masking the fact that not all `/kubernetes/ops` requests were creating kubernetes resource entries, so these were corrected.
=> Task not found response

pkg/http/core/kubernetes/deploy.go, pkg/http/core/kubernetes/deploy_test.go, pkg/kubernetes/strategy.go, pkg/kubernetes/strategy_test.go
This PR:
- Implements support of the `strategy.spinnaker.io/use-source-capacity` annotation as described in [Spinnaker docs](https://spinnaker.io/docs/reference/providers/kubernetes-v2/#strategy)
- Although `use-source-capacity` is the only strategy annotation implements, the `strategy.go` file contains functions for retrieving the remaining Spinnaker strategy annotations, which can be used in the future
- max-version-history
- release
- replace
=> Spinnaker strategy use-source-capacity

Makefile, pkg/http/core/kubernetes/scale.go, pkg/http/core/kubernetes/scale_test.go
This PR:
- Adds support for scaling replicaSets
- Updates Makefile linter
- Skip tests
- Extends timeout
=> Support scaling replicaSets

internal/api/core/applications.go, internal/api/core/applications_test.go, internal/api/core/core_test.go, internal/api/core/kubernetes/cleanup.go, internal/api/core/kubernetes/deploy.go, internal/api/core/kubernetes/kubernetes_test.go, internal/api/core/kubernetes/rollback.go, internal/api/core/kubernetes/rollback_test.go, internal/api/core/manifest.go, internal/api/core/manifest_test.go, internal/api/core/payload_test.go, internal/kubernetes/filter.go, internal/kubernetes/filter_test.go, internal/kubernetes/label_selector.go, internal/kubernetes/label_selector_test.go, internal/kubernetes/version.go
- adds exhaustive responses in tests that include the wrong application in the `moniker.spinnaker.io/application` to verify implementation is working correctly
- adds the func `kubernetes.DefaultLabelSelector()` which returns the label selector `app.kubernetes.io/managed-by in (spinnaker,spinnaker-operator)`
- filters all listed resources according to the `moniker.spinnaker.io/application=<APPLICATION_NAME>` after listing
- fixes issue where annotation `moniker.spinnaker.io/application` value was wrapped in double quotes
- removes any instance of using a label selector to select `app.kubernetes.io/name=<APPLICATION_NAME>`
- simplifies the manifest filter to two functions that are directly callable: `FilterOnAnnotation` and `FilterOnLabelExists`
=> Use application annotation to filter on Clusters page

internal/api/core/kubernetes/deploy.go, internal/api/core/kubernetes/deploy_test.go, internal/kubernetes/traffic.go, internal/kubernetes/traffic_test.go
- adds support for annotation `traffic.spinnaker.io/load-balancers`
Notes:
- Some of the errors returned start with a capital letter, like `Service selector must have no label keys in common with target workload`. This is to align with the Java source code and provide a similar experience to OSS Clouddriver. It is not good practice for Go errors to begin with a capital letter, but I think we should do it in this case.
=> Add support for traffic load balancers annotation

internal/api/core/kubernetes/kubernetes_test.go, internal/api/core/kubernetes/ops.go, internal/api/core/kubernetes/patch.go, internal/api/core/kubernetes/patch_test.go, internal/kubernetes/artifact.go
- adds support for artifacts in the Patch (Manifest) stage
Notes:
- we only need to support binding artifacts for patch types of "strategic" or "merge" as per the documentation https://spinnaker.io/docs/guides/user/kubernetes-v2/patch-manifest/#override-artifacts
=> Add ability to bind artifacts for Patch (Manifest) stage

internal/api/core/manifest.go, internal/api/core/manifest_test.go
- Adds support for `largest` and `smallest` targets as per [source code](https://github.com/spinnaker/clouddriver/blob/0fb3e75faa586f213a39c9fd4145f08e519b2e97/clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/controllers/ManifestController.java#L132-L148)
- Adds test cases for `largest` and `smallest` targets
- Removes error if attempting to get `oldest` target and only one resource is returned - in this case that is the oldest resource
=> fix finding oldest manifest coords when only one resource found

internal/api/core/manifest.go, internal/api/core/manifest_test.go, internal/api/server.go
- Adds support for finding a manifest dynamically by criteria `largest` and `smallest`
- Changes nomenclature for specifying manifest from `target` to `criteria` as this seems to be how it works in the [source code](https://github.com/spinnaker/clouddriver/blob/0fb3e75faa586f213a39c9fd4145f08e519b2e97/clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/controllers/ManifestController.java#L113)
=> Support finding manifest dynamically by size

internal/api/core/kubernetes/deploy.go, internal/api/core/kubernetes/deploy_test.go, internal/api/core/kubernetes/runjob.go, internal/api/core/kubernetes/runjob_test.go, internal/kubernetes/annotation.go, internal/kubernetes/annotation_test.go
- Fixes annotating `artifact.spinnaker.io/location` for objects that do not specify a namespace
Notes:
- There were a few ways to do this, but I decided to not mess with any of the logic in the `internal/api/core/kubernetes/*` files, except for passing the namespace to the `AddSpinnakerAnnotations` function. I felt this was much safer than moving any logic that the dynamic client's [helper](https://github.com/homedepot/go-clouddriver/blob/master/internal/kubernetes/unstructured.go#L51) is performing to check if a kind is cluster scoped. This is much less intrusive and I did not want to mess with anything responsible for applying the manifest to a cluster as that code is copied from the `kubectl` source code.
- OSS annotates an empty string for cluster-scoped resources, so the annotation …
=> Fix location annotation

internal/api/core/applications.go, internal/api/core/applications_test.go
Defensively checks the array size parsed from the `name` parameter, which is expected to have a format of `kind name` on these endpoints.
- `GET /applications/:application/serverGroups/:account/:location/:name`
- `GET /applications/:application/jobs/:account/:location/:name`
When the name parameter value doesn't contain a space, then the application panics with an `index out of range` error and returns a `500 (Internal Server Error)` status code.  This change handles the unexpected value and returns a `400 (Bad Request)` response instead.
=> Index out of range error

internal/api/core/kubernetes/deploy.go, internal/api/core/kubernetes/deploy_test.go, internal/api/core/kubernetes/restart.go, internal/api/core/kubernetes/restart_test.go, internal/api/core/kubernetes/rollback.go, internal/api/core/kubernetes/rollback_test.go, internal/api/core/kubernetes/runjob.go, internal/api/core/kubernetes/runjob_test.go, internal/api/core/kubernetes/scale.go, internal/api/core/kubernetes/scale_test.go, internal/kubernetes/annotation.go, internal/kubernetes/annotation_test.go, internal/kubernetes/cached/disk/diskfakes/fake_cache_round_tripper.go, internal/kubernetes/client.go, internal/kubernetes/kubernetesfakes/fake_client.go, internal/kubernetes/kubernetesfakes/fake_clientset.go, internal/kubernetes/kubernetesfakes/fake_controller.go, internal/kubernetes/namespace.go, internal/kubernetes/namespace_test.go
This PR sets the namespace in the manifests before processing them.  For namespace-scoped Kubernetes kinds, the order of precedence for determining the namespace is
- the namespace of a namespace-scoped provider
- the namespace override from the `/kubernetes/ops` request
- the literal `default`, when the namespace is not specified in the manifest
- the namespace in the manifest, when specified - that is, left unchanged
By setting the namespace early in the processing, downstream logic is assured that the namespace will always have a value and doesn't have to do any namespace determination of its own (or equate `"default"` with `""`).  The code has been refactored to remove this redundant processing.
This corrects an issue with handling the `traffic.spinnaker.io/load-balancers` annotation …
=> Set namespace on manifests

internal/api/core/kubernetes/deploy.go, internal/api/core/kubernetes/deploy_test.go, internal/api/core/kubernetes/ops.go
- Adds support for Spinnaker managed traffic
Notes:
This is the error that is returned when the annotation `traffic.spinnaker.io/load-balancers` is already set:
```
manifest already has traffic.spinnaker.io/load-balancers annotation set to ["service test-service"]. Failed attempting to set it to [service test-service, service test-service2]
```
I did a simple `strings.Join(...)` on the array to build the error which is why the services in the second array are not wrapped in double quotes. If this is bothersome please request changes to build the string array.
=> add support for spinnaker managed traffic

internal/api/core/kubernetes/ops.go, internal/api/core/manifest.go, internal/api/core/manifest_test.go, internal/api/core/payload_test.go, internal/kubernetes/cached/disk/diskfakes/fake_cache_round_tripper.go, internal/kubernetes/clientset.go, internal/kubernetes/kubernetesfakes/fake_client.go, internal/kubernetes/kubernetesfakes/fake_clientset.go, internal/kubernetes/kubernetesfakes/fake_controller.go
- Adds support for getting manifest events if the query param `includeEvents` is not set to false
Example events for a pod from the clusters page:
Notes:
- We run requests to grab the manifest and events concurrently
- We use a `select` when grabbing the manifest to handle errors or a successful response
- Failure to grab events is silent and still returns the manifest
- I used the Kubernetes Clientset's `CoreV1().Events(namespace)` to grab any events regardless of kind. In testing this works for Deployments, ReplicaSets, and Pods, even though not all of these are part of the core API group
- See [this StackOverflow post](https://stackoverflow.com/questions/53638778/kubernetes-go-client-list-events) for source code used to grab events
=> Add support for getting manifest events

internal/kubernetes/provider.go, internal/sql/client_test.go
To support a large certificate chains, changed the data type of the `kubernetes_providers.ca_data` column from `VARCHAR(8196)` to `TEXT`.
For MySQL, the maximum length of a `VARCHAR` column is `65,535`, but effectively is only `21,844` as described [here](https://newbedev.com/equivalent-of-varchar-max-in-mysql).  Changing to a `TEXT` data type allows for a true limit of `65,535` bytes.
=> Support large CA certificate chains

internal/api/core/applications.go, internal/api/core/applications_test.go, internal/api/core/payload_test.go
This PR adds the necessary functions to show the user in the clusters page if a server group is enabled or disabled.
Here is an example server group (Replica Set) that is enabled (receiving traffic from its managed load balancers in the `traffic.spinnaker.io/load-balancers` annotation).
We can see upon clicking the server group that under *Replica Set Actions* we have the option to "Disable" the Replica Set.
Clicking "Disable" patches the Replica Set and its pods' templates to not be fronted by its managed load balancer. It is then shown as disabled in the right pane.
The clusters page now shows this server group to be "Disabled" and is greyed-out, however its detached load balancer is still associated with the server group.
Under *Replica Set Actions* for this server group we now have …
=> Add support for enabled/disabled manifests in clusters page

internal/api/core/applications.go, internal/api/core/applications_test.go, internal/api/core/payload_test.go, internal/api/server.go
- implements `/applications/{application}/clusters/{account}/{clusterName}/kubernetes` endpoint
This is used when checking cluster size in a *Check Preconditions* stage. Here is an example of an intentionally failed stage:
Notes:
- This just lists a given kind and filters on application and cluster name. The only logic around changing the kind is if the requested cluster is kind `deployment` in which case we actually list `replicaSets`.
- I decided to ignore much of the response (instances, instance counts, etc) as they did not seem important for the use-case.
=> Add ability to list clusters by name

internal/api/core/kubernetes/delete.go, internal/api/core/kubernetes/delete_test.go
This is the expected result in OSS Clouddriver - to return a status OK when no kinds are selects.
=> Error on delete manifest requests where there are no kinds

cmd/clouddriver/clouddriver.go, internal/kubernetes/cached/disk/cached_discovery_test.go, internal/kubernetes/cached/memory/memcache.go, internal/kubernetes/cached/memory/memcache_test.go, internal/kubernetes/cached/memory/memory_suite_test.go, internal/kubernetes/cached/memory/round_tripper.go, internal/kubernetes/cached/memory/round_tripper_test.go, internal/kubernetes/client.go, internal/kubernetes/controller.go, internal/kubernetes/controller_test.go
*Note: I am currently just looking for feedback on implementation and features while this is being tested in our sandbox*.
This PR converts Go Clouddriver to use an in-memory cache store *by default* for both its Kubernetes API discovery and HTTP response caching. It is configurable by setting the environment variable `KUBERNETES_USE_DISK_CACHE` to `true`.
I rewrote the [memory/memcache.go](https://github.com/kubernetes/client-go/blob/master/discovery/cached/memory/memcache.go) to be logically similar to [disk/cached_discovery.go](https://github.com/kubernetes/client-go/blob/master/discovery/cached/disk/cached_discovery.go).
I added a roundtripper that uses `github.com/gregjones/httpcache` for its in-memory HTTP request caching. The disk caching implementation uses a directory to store …
=> Use in memory cache for Kubernetes API discovery and HTTP requests

internal/api/core/search.go, internal/api/core/search_test.go, internal/controller.go, internal/controller_test.go, internal/kubernetes/cached/memory/memcache.go, internal/kubernetes/controller.go, internal/kubernetes/controller_test.go
- no longer concurrently make calls to SQL to grab accounts on the search endpoint. Instead we list all providers and filter out any the user does not have access to.
- change how we handle mutex locks on the mem cache client so we don't block concurrent listing of server groups and resources (this is bad for clusters that we timeout reaching)
- store cached configs and clients with unique keys based on their config host name and timeout - this prevents us using a config with the wrong timeout for specific operations
=> Fix memcache concurrency issues and list all providers before searching

internal/api/core/search.go, internal/api/core/search_test.go
Ignores searching for kinds "applications", "instances", "loadBalancers", "projects", and "securityGroups" to make the search page faster.
=> Ignore search types

internal/api/server.go
Deployments rely on this endpoint for some reason, so we can't use cache-control here.
=> remove cache control from applications endpoint

internal/kubernetes/clientset.go
- set the `involvedObject.kind` field selector when grabbing events. Failure to do this will grab and associate events for the wrong kind if the name of the resource is the same.
=> Fix associating events with the wrong kind

internal/kubernetes/clientset.go
When using the field selector `involvedObject.kind=SomeKind` to grab events, the kind is always expected to start with a capital letter. Grabbing events from a pipeline stage were working fine as the request to grab a manifest would send something like `Deployment my-deployment`, but getting events in the clusters page was failing because `deployment` was lowercased. This fixes that problem.
=> Always grab involved object kind field selector by correct casing

internal/api/core/kubernetes/deploy.go, internal/api/core/kubernetes/deploy_test.go, internal/api/core/kubernetes/runjob.go, internal/api/core/kubernetes/runjob_test.go, internal/kubernetes/client.go, internal/kubernetes/kubernetesfakes/fake_client.go
Implements the [replace strategy](https://spinnaker.io/docs/reference/providers/kubernetes-v2/#strategy)
> As of Spinnaker 1.14, you can force Spinnaker to use replace instead of of apply while deploying a Kubernetes resource. This may be useful for resources such as ConfigMap which may exceed the annotation size limit of 262144 characters.
>
> When set to 'true' for a versioned resource, this will update your resources using replace.
This only implements replace in `deploy.go`, there are other places that apply is being called - should they be changed as well?
- restart.go
- rollback.go
- runjob.go
- scale.go
=> Implements replace strategy

internal/api/core/applications.go, internal/api/core/applications_test.go, internal/api/core/project_test.go
I ran a few stress tests locally and found that unmarshaling unto Kubernetes objects (such as a Pod, ReplicaSet, StatefulSet, etc) in order to grab object info was greatly increasing the time complexity of the applications API. Instead, we now use built-in functions from the `unstructured` package to grab information from an unstructured object.
=> Reduce Applications API complexity

internal/api/core/applications.go, internal/api/core/applications_test.go, internal/api/core/core_test.go, internal/controller.go, internal/controller_test.go
For Spinnaker applications that have dozens of accounts associated with them, we're seeing slow concurrent calls to grab each Kubernetes provider needed to populate the Clusters page in Spinnaker. This is because we are making one SQL call to list all account names associated with a given application (from the `kubernetes_resources` table), then making separate SQL calls for each of these accounts in a go routine to the `kubernetes_providers` table to get the provider info. 
This PR solves this problem by:
- provides a new function `KubernetesProvidersForAccountsWithTimeout` that grabs ALL providers and generates a list for the accounts list passed in
- removing the call to `GetKubernetesProvider` in the Application's API and replacing it with a single call to …
=> Add ability to list providers for given accounts

internal/api/core/core_test.go, internal/api/core/task.go, internal/api/core/task_test.go
After a Kubernetes operation (like deploy/delete/etc), Orca monitors the `/task/:id` endpoint to grab this operation's status. If we do not return a task object then Orca will hit a null pointer exception [here](https://github.com/spinnaker/orca/blob/master/orca-clouddriver/src/main/groovy/com/netflix/spinnaker/orca/clouddriver/tasks/MonitorKatoTask.groovy#L224) since a Clouddriver error does not contain a `$.status` field. This happens very rarely, but it results in a non-descriptive `Unexpected task failure` error in the UI.
This PR fixes this issue by always returning a task, regardless of the failure type. It wraps the errors in descriptive text for the task status. It makes use of the field `retryable` so Orca can know that even though a task failed for certain errors, it can retry. …
=> Fix unexpected task failure

internal/kubernetes/provider.go, internal/sql/client_test.go
32 was a bit too short for the "provider-context" trick of using "providerName.context" as the provider in g-clouddriver.
In our use case, we have a single provider (Conjur) which provides many credentials for many clusters, so the specific cluster an account is associated with needs to be provided as well.  The "trick" here was to provide a context as part of the provider name, using "conjur.context" or similar.  In our case, we would also like to have more than one provider of that type, but we will address that in Arcade later.   For now, just making the string here longer is sufficient.
I chose 128 as a "probably long enough" length, but I'd be tempted to ask why it should not be "text" -- and indeed, why any of the fields need lengths at all here.
=> increase tokenprovider length

internal/api/core/credentials.go
This is covered by existing tests.
With many providers, `/credentials?expand=true` can be a pretty expensive operation even when explicit namespaces are configured in the provider.  This change avoids using a goproc and a channel just to return a static string, and the associated repeated linear search to add the found namespaces.
In my testing, with an extreme of 10,000 providers, this reduces the time to respond from 2 seconds to around 250 ms when all have namespaces.
I suspect some amount of cache would be useful here for the k8x queries, since those are unlikely to rapidly change and likely expensive.
=> avoid goproc for explicit namespaces

internal/kubernetes/client.go
Fix for [Issue 157](https://github.com/homedepot/go-clouddriver/issues/157).  
Using info.Get() checks if the resource exists and if it does exist then it updates the info.Object() field to that existing resource.  This causes the existing resource to be used instead of the new object.  Using helper.Get() just returns the object if it exists or an IsNotFound error if it does not exist allowing the new object in info.Object() to be used to replace the existing object.
Initial config map to be deployed:
Deployed config map:
Updated config map with replace set to true and versioned set to false:
New deployed config map with updates:
=> Fix replace for non-versioned resources

internal/api/core/kubernetes/deploy.go, internal/api/core/kubernetes/patch.go, internal/api/core/kubernetes/patch_test.go, internal/api/core/kubernetes/runjob.go, internal/api/core/kubernetes/runjob_test.go, internal/kubernetes/artifact.go, internal/kubernetes/artifact_test.go
This change adds a function `isBindable` which validates that an artifact's provider account is the same as the account passed in with the deployment request. The `BindArtifacts` function uses this to exclude artifacts that don't exist in the target cluster, thus preventing the behavior detailed in [this issue](https://github.com/homedepot/go-clouddriver/issues/158) which was causing certain deployments to fail.
I also updated the unit tests to verify the expected behavior.
Tests without the bug fix: 
Tests with the bug fix:
=> fix versioning broken when deploying to multiple clusters with same artifact

internal/api/v1/provider.go, internal/api/v1/provider_test.go, internal/sql/client.go, internal/sql/client_test.go
- fixes gorm scan error for `sql.Client.GetKubernetesProvider` by ensuring scan arguments and queried columns are equal
- returns `gorm.ErrRecordNotFound` instead of nil error when the provider struct is empty, i.e. does not exist in DB, for `sql.Client.GetKubernetesProvider` and `sql.Client.GetKubernetesProviderAndPermissions`
=> fix(sql): fix gorm scan error found in smoketests

.github/workflows/build.yml, internal/api/core/kubernetes/deploy.go, internal/api/core/kubernetes/deploy_test.go, internal/kubernetes/unstructured.go
Kubernetes expects manifest annotations to be a map with string values. This PR resolves the bug indirectly discovered in [this issue](https://github.com/homedepot/go-clouddriver/issues/168) by forcing all non-string annotations to `string` type when converting to a kubernetes `unstructured.Unstructured` object.
Failure because annotations were getting cleared out, thus `strategy.spinnaker.io/replace` was missing:
Successful deployment after fix:
=> fix(kubernetes): non-string annotation values cause the annotation map in a manifest's Go representation to be empty 

MAINTAINERS.md, internal/kubernetes/custom_kind.go
- Adds code to load custom kinds config from file only on the first invocation of `getCustomKindConfig()`; future calls will retrieve the value from memory
The debugging logs below show that on the first call, the config data is nil and so it reads the JSON file from disk, but on subsequent calls, it skips that block and uses the in-memory non-nil config data.
=> [CN-3941]: Improve loading of custom kinds config file
